# Set some aliases
# alias ls="ls --color"
# alias mc="mc -u"
# alias m="/bin/mailgrep"
# alias ls="ls -G"
# alias l="ls -las"
 alias psgrep="ps -auxx|grep -i"
# alias p="pine"
 alias dus="du-hsckx * | sort -nr"
# alias platinum="platinum -ljason platinum"
# alias bronze="bronze -ljason bronze.mednet-tech.com"
# alias cad="cadmium -ljason cadmium.mednet-tech.com"
# alias iron="iron -ljason iron.mednet-tech.com"
# alias chronos="chrono -ljason 208.109.124.56"
# alias sites="sites -lroot mednet-sites.com"
# alias sites4="sites4 -lroot mednet-sites4.com"
# alias sites5="sites5 -lroot mednet-sites5.com"
# alias sites6="sites6 -lroot mednet-sites6.com"
# alias tung="tungsten -ljason tungsten.mednet-tech.com"
# alias merc="mercury -ljason mercury.mednet-tech.com"
# alias gemini="gemini -ljason 66.11.131.36"
# alias devloc="devloc -ljason 192.168.254.172"
 alias mysql=/usr/local/mysql/bin/mysql
 alias mysqladmin=/usr/local/mysql/bin/mysqladmin
 alias stop_mysql='sudo launchctl unload -w /Library/LaunchDaemons/com.mysql.mysqld.plist'
 alias start_mysql='sudo launchctl load -w /Library/LaunchDaemons/com.mysql.mysqld.plist'
 alias dev="ssh -ljason 174.129.38.52"
 alias prod="ssh -ljason ec2.wajig.com"
 alias pizzy="ssh 184.73.184.172"
 alias rbox="ssh micro.wajig.com"
alias t='python ~/t/t.py --task-dir ~/tasks --list todo.txt --delete-if-empty'
alias b='python ~/t/t.py --task-dir . --list bugs --delete-if-empty'
 # #alias zxc="cmatrix -ab"
# #alias pb='less /home/pete/tel | grep -i'
# alias cdd='cd $OLDPWD'
